version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-anaconda-image
    read_only: false
    ports:
    - "8888:8888"
    volumes:
    - .:/working-directory